[package]
name = "crc-rocksoft"
version = "0.1.1"
authors = ["ypoluektovich"]
description = "A parameterized CRC implementation"

[dependencies]
bit_reverse = "0.1.5"

[dev-dependencies]
lazy_static = "0.2.4"
